using System;
using System.Collections.Generic;
using UnityEngine;

namespace LoogaSoft.Instancing
{
    /// <summary>Authors mesh placements into explicit containers. Generated data remains usable without this authoring component.</summary>
    [ExecuteAlways, DisallowMultipleComponent]
    [UnityEngine.Scripting.APIUpdating.MovedFrom(true, "LoogaSoft.Terrain.Instances", "LoogaSoft.Terrain.Instances", "MeshScatterAuthoring")]
    public sealed class MeshScatterAuthoring : MonoBehaviour
    {
        /// <summary>One prototype container and its relative selection weight.</summary>
        [Serializable]
        public struct Target
        {
            /// <summary>Container that receives this prototype's generated placements.</summary>
            public InstanceContainer Container;
            /// <summary>Relative prototype probability. Zero excludes the target.</summary>
            [Min(0)] public float Weight;
        }

        [Serializable]
        private struct MaskStroke
        {
            public Matrix4x4 LocalToBrush;
            public float Amount;
            public float Falloff;
        }

        [SerializeField] private MeshFilter _surface;
        [SerializeField] private PlacementExclusion[] _exclusions = Array.Empty<PlacementExclusion>();
        [SerializeField] private Target[] _targets = Array.Empty<Target>();
        [SerializeField] private MeshScatterSettings _settings = new();
        [SerializeField, Range(0, 1)] private float _baseMask = 1;
#if UNITY_EDITOR
        [SerializeField] private bool _autoRefresh = true;
#endif
        [SerializeField, HideInInspector] private string _sourceId;
        [SerializeField, HideInInspector] private List<MaskStroke> _strokes = new();
        [SerializeField, HideInInspector] private InstanceContainer[] _previousTargets = Array.Empty<InstanceContainer>();
        private MeshScatterSurface _snapshot;
        private Mesh _mesh;
        private Matrix4x4 _surfaceMatrix;
        private Matrix4x4[] _targetMatrices = Array.Empty<Matrix4x4>();
        private List<MeshScatterSurface.Sample>[] _triangles;
        private bool _needsRebuild = true;
        private bool _subscriptionsDirty;
        private readonly HashSet<PlacementExclusion> _subscribedExclusions = new();
        private Bounds? _pendingExclusionBounds;

        /// <summary>Configured source mesh filter.</summary>
        public MeshFilter Surface => _surface;
        /// <summary>Last generation failure, or null after a successful generation.</summary>
        public string Diagnostic { get; private set; }
        /// <summary>Triangle regions regenerated by the last operation.</summary>
        public int LastRegeneratedTriangles { get; private set; }
        /// <summary>Generated placement count across all targets.</summary>
        public int GeneratedCount { get; private set; }
        /// <summary>Number of saved brush dabs.</summary>
        public int StrokeCount => _strokes.Count;

        #region Lifecycle
        private void OnEnable()
        {
            SubscribeExclusions(true);
            RequestRebuild();
        }
        private void OnDisable() => SubscribeExclusions(false);

        /// <summary>Assign explicit road, water or gameplay masks without changing their source geometry.</summary>
        public void SetExclusions(PlacementExclusion[] exclusions)
        {
            SubscribeExclusions(false);
            _exclusions = exclusions == null ? Array.Empty<PlacementExclusion>() : (PlacementExclusion[])exclusions.Clone();
            if (isActiveAndEnabled)
            {
                SubscribeExclusions(true);
            }
            RequestRebuild();
        }

        private void SubscribeExclusions(bool subscribe)
        {
            foreach (var exclusion in _subscribedExclusions)
            {
                if (exclusion)
                {
                    exclusion.Changed -= ExclusionChanged;
                }
            }
            _subscribedExclusions.Clear();
            _subscriptionsDirty = false;
            if (!subscribe) return;
            foreach (var exclusion in _exclusions ?? Array.Empty<PlacementExclusion>())
            {
                if (exclusion && _subscribedExclusions.Add(exclusion))
                {
                    exclusion.Changed += ExclusionChanged;
                }
            }
        }

        private void ExclusionChanged(Bounds bounds)
        {
            if (_pendingExclusionBounds.HasValue)
            {
                bounds.Encapsulate(_pendingExclusionBounds.Value);
            }
            _pendingExclusionBounds = bounds;
            Diagnostic = null;
        }

        private void OnValidate()
        {
            _subscriptionsDirty = true;
            RequestRebuild();
        }

        /// <summary>Apply queued mask changes. Call this after runtime road or water regeneration.</summary>
        public void ProcessExclusionChanges()
        {
            if (_subscriptionsDirty)
            {
                SubscribeExclusions(isActiveAndEnabled);
            }
            if (!_pendingExclusionBounds.HasValue || !_surface) return;
            Bounds bounds = _pendingExclusionBounds.Value;
            if (_needsRebuild || _snapshot == null || TransformsChanged())
            {
                Regenerate();
            }
            else
            {
                Generate(bounds, false);
            }
            _pendingExclusionBounds = null;
        }

        private void LateUpdate()
        {
#if UNITY_EDITOR
            if (Application.isPlaying || !_autoRefresh || Diagnostic != null || _surface == null || _targets.Length == 0) return;
            if (!_needsRebuild && !TransformsChanged() && !_pendingExclusionBounds.HasValue && !_subscriptionsDirty) return;
            try
            {
                ProcessExclusionChanges();
                if (_needsRebuild || TransformsChanged())
                {
                    Regenerate();
                }
            }
            catch (Exception exception)
            {
                Diagnostic = exception.Message;
                // Retry after an explicit edit, not on every editor frame.
                _needsRebuild = false;
            }
#endif
        }
        #endregion

        #region Authoring
        /// <summary>Configure a mesh and weighted targets. This operation does not change source mesh or prefab assets.</summary>
        public void Configure(MeshFilter surface, Target[] targets, MeshScatterSettings settings, float baseMask = 1)
        {
            if (settings == null)
            {
                throw new ArgumentNullException(nameof(settings));
            }
            settings.Validate();
            if (!float.IsFinite(baseMask) || baseMask < 0 || baseMask > 1)
            {
                throw new ArgumentOutOfRangeException(nameof(baseMask));
            }
            _surface = surface;
            _targets = targets == null ? Array.Empty<Target>() : (Target[])targets.Clone();
            _settings = settings.Copy();
            _baseMask = baseMask;
            RequestRebuild();
            Regenerate();
        }

        /// <summary>Queue a complete snapshot refresh after mesh or authoring data changes.</summary>
        public void RequestRebuild()
        {
            _needsRebuild = true;
            Diagnostic = null;
        }

        /// <summary>Return current and former targets for editor Undo recording.</summary>
        public InstanceContainer[] GetAffectedContainers()
        {
            var result = new List<InstanceContainer>();
            foreach (var target in _targets)
            {
                if (target.Container != null && !result.Contains(target.Container))
                {
                    result.Add(target.Container);
                }
            }
            foreach (var target in _previousTargets)
            {
                if (target != null && !result.Contains(target))
                {
                    result.Add(target);
                }
            }
            return result.ToArray();
        }

        /// <summary>Remove all saved brush dabs and regenerate from the base mask.</summary>
        public void ClearMask()
        {
            _strokes.Clear();
            RequestRebuild();
            Regenerate();
        }

        /// <summary>Apply a world-space brush dab. Negative amount erases; positive amount paints.</summary>
        public void Paint(Vector3 worldCenter, float radius, float amount, float falloff = 1)
        {
            if (_surface == null || !float.IsFinite(radius) || radius <= 0 || !float.IsFinite(amount) ||
                Mathf.Abs(amount) > 1 || !float.IsFinite(falloff) || falloff < 0 ||
                !float.IsFinite(worldCenter.x) || !float.IsFinite(worldCenter.y) || !float.IsFinite(worldCenter.z))
            {
                throw new ArgumentException("Use a valid surface, finite brush center, positive radius and an amount between -1 and 1.");
            }
            if (_strokes.Count >= 4096)
            {
                throw new InvalidOperationException("This surface has 4096 brush dabs. Split the authoring surface before adding more dabs.");
            }
            if (_needsRebuild || TransformsChanged())
            {
                Regenerate();
            }
            _strokes.Add(new MaskStroke
            {
                LocalToBrush = Matrix4x4.TRS(worldCenter, Quaternion.identity, Vector3.one * radius).inverse * _surface.transform.localToWorldMatrix,
                Amount = amount,
                Falloff = falloff
            });
            try
            {
                Generate(new Bounds(worldCenter, Vector3.one * radius * 2), false);
            }
            catch
            {
                _strokes.RemoveAt(_strokes.Count - 1);
                RequestRebuild();
                throw;
            }
        }

        /// <summary>Refresh all geometry and placements. Stable triangle/candidate IDs keep existing renderer handles.</summary>
        public void Regenerate() => Generate(null, true);

        /// <summary>Refresh edited geometry inside a bound containing its old and new positions. Topology changes require Regenerate.</summary>
        public void InvalidateSurface(Bounds changedWorldBounds) => Generate(changedWorldBounds, true);

        /// <summary>Pick the source mesh without creating a physics collider.</summary>
        public bool Raycast(Ray ray, out Vector3 point, out Vector3 normal)
        {
            point = normal = default;
            if (_surface == null || _surface.sharedMesh == null) return false;
            if (_snapshot == null || _mesh != _surface.sharedMesh || _surfaceMatrix != _surface.transform.localToWorldMatrix)
            {
                _needsRebuild = true;
                Capture();
            }
            return _snapshot.Raycast(ray, out point, out normal);
        }
        #endregion

        private void Generate(Bounds? changed, bool capture)
        {
            if (_surface == null || _surface.sharedMesh == null)
            {
                throw new InvalidOperationException("Assign the mesh surface before generation.");
            }
            _settings.Validate();
            float[] weights = ValidateTargets();
            if (string.IsNullOrEmpty(_sourceId))
            {
                _sourceId = Guid.NewGuid().ToString("N");
            }
            string prefix = "mesh:" + _sourceId + ":";
            bool all = !changed.HasValue || _needsRebuild || TransformsChanged();
            var oldSnapshot = _snapshot;
            if (capture || all)
            {
                Capture();
            }
            _snapshot.ValidateBudget(_settings);
            if (_triangles == null || _triangles.Length != _snapshot.TriangleCount)
            {
                all = true;
                _triangles = new List<MeshScatterSurface.Sample>[_snapshot.TriangleCount];
            }
            LastRegeneratedTriangles = 0;
            for (int i = 0; i < _triangles.Length; i++)
            {
                if (!all && !_snapshot.GetBounds(i).Intersects(changed.Value) &&
                    (oldSnapshot == null || !oldSnapshot.GetBounds(i).Intersects(changed.Value)))
                {
                    continue;
                }
                var samples = new List<MeshScatterSurface.Sample>();
                _snapshot.GenerateTriangle(i, prefix, _settings, weights, Mask, samples);
                _triangles[i] = samples;
                LastRegeneratedTriangles++;
            }
            var containers = GetAffectedContainers();
            var outputs = new Dictionary<InstanceContainer, List<InstanceContainer.Placement>>();
            foreach (var container in containers)
            {
                var kept = new List<InstanceContainer.Placement>();
                foreach (var placement in container.CopyPlacements())
                {
                    if (!placement.Id.StartsWith(prefix, StringComparison.Ordinal))
                    {
                        kept.Add(placement);
                    }
                }
                outputs.Add(container, kept);
            }
            int count = 0;
            foreach (var samples in _triangles)
            {
                foreach (var sample in samples)
                {
                    var target = _targets[sample.Target].Container;
                    outputs[target].Add(new InstanceContainer.Placement
                    {
                        Id = sample.Id,
                        Position = target.transform.InverseTransformPoint(sample.Position),
                        EulerAngles = (Quaternion.Inverse(target.transform.rotation) * sample.Rotation).eulerAngles,
                        Scale = Vector3.one * (sample.Scale / target.transform.lossyScale.x)
                    });
                    count++;
                }
            }
            // Validate all output records before changing the first container.
            var batches = new Dictionary<InstanceContainer, InstanceContainer.Placement[]>();
            foreach (var pair in outputs)
            {
                batches.Add(pair.Key, InstanceContainer.CopyValidated(pair.Value.ToArray()));
            }
            foreach (var pair in batches)
            {
                pair.Key.SetPlacements(pair.Value);
            }
            _previousTargets = Array.ConvertAll(_targets, target => target.Container);
            _targetMatrices = Array.ConvertAll(_targets, target => target.Container.transform.localToWorldMatrix);
            _needsRebuild = false;
            GeneratedCount = count;
            Diagnostic = null;
#if UNITY_EDITOR
            if (!Application.isPlaying)
            {
                UnityEditor.EditorUtility.SetDirty(this);
                foreach (var container in containers)
                {
                    UnityEditor.EditorUtility.SetDirty(container);
                    if (!UnityEditor.SceneManagement.EditorSceneManager.IsPreviewScene(container.gameObject.scene))
                    {
                        UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(container.gameObject.scene);
                    }
                }
            }
#endif
        }

        private float[] ValidateTargets()
        {
            if (_targets.Length == 0)
            {
                throw new InvalidOperationException("Assign at least one prototype container.");
            }
            var seen = new HashSet<InstanceContainer>();
            var weights = new float[_targets.Length];
            double sum = 0;
            for (int i = 0; i < _targets.Length; i++)
            {
                var target = _targets[i];
                if (target.Container == null || !seen.Add(target.Container) || !float.IsFinite(target.Weight) || target.Weight < 0)
                {
                    throw new ArgumentException("Assign distinct containers with finite, nonnegative weights.");
                }
                var matrix = target.Container.transform.localToWorldMatrix;
                Vector3 x = matrix.GetColumn(0), y = matrix.GetColumn(1), z = matrix.GetColumn(2);
                float scale = x.magnitude;
                if (!float.IsFinite(scale) || scale < 0.0001f || matrix.determinant <= 0 ||
                    target.Container.transform.lossyScale.x <= 0 || target.Container.transform.lossyScale.y <= 0 || target.Container.transform.lossyScale.z <= 0 ||
                    Mathf.Abs(y.magnitude - scale) > scale * 0.0001f || Mathf.Abs(z.magnitude - scale) > scale * 0.0001f ||
                    Mathf.Abs(Vector3.Dot(x.normalized, y.normalized)) > 0.0001f ||
                    Mathf.Abs(Vector3.Dot(x.normalized, z.normalized)) > 0.0001f || Mathf.Abs(Vector3.Dot(y.normalized, z.normalized)) > 0.0001f)
                {
                    throw new ArgumentException("Scatter target containers require positive uniform scale without parent shear.");
                }
                weights[i] = target.Weight;
                sum += target.Weight;
            }
            if (sum <= 0 || sum > float.MaxValue)
            {
                throw new ArgumentException("At least one target must have a positive weight, with a finite total.");
            }
            foreach (var other in FindObjectsByType<MeshScatterAuthoring>(FindObjectsInactive.Include, FindObjectsSortMode.None))
            {
                if (other == this || string.IsNullOrEmpty(_sourceId) || other._sourceId != _sourceId)
                {
                    continue;
                }
                foreach (var target in other._targets)
                {
                    if (seen.Contains(target.Container))
                    {
                        throw new InvalidOperationException("Duplicated scatter identity targets the same container. Use separate targets or create a new authoring component.");
                    }
                }
            }
            return weights;
        }

        private void Capture()
        {
            var matrix = _surface.transform.localToWorldMatrix;
            var snapshot = new MeshScatterSurface(_surface.sharedMesh, matrix);
            _snapshot = snapshot;
            _mesh = _surface.sharedMesh;
            _surfaceMatrix = matrix;
        }

        private bool TransformsChanged()
        {
            if (_surface == null || _snapshot == null || _mesh != _surface.sharedMesh ||
                _surfaceMatrix != _surface.transform.localToWorldMatrix || _targetMatrices.Length != _targets.Length) return true;
            for (int i = 0; i < _targets.Length; i++)
            {
                if (_targets[i].Container == null || _targets[i].Container.transform.localToWorldMatrix != _targetMatrices[i]) return true;
            }
            return false;
        }

        private float Mask(Vector3 localPosition)
        {
            float result = _baseMask;
            foreach (var stroke in _strokes)
            {
                float distance = stroke.LocalToBrush.MultiplyPoint3x4(localPosition).magnitude;
                if (distance >= 1)
                {
                    continue;
                }
                float weight = stroke.Falloff <= 0 ? 1 : Mathf.Pow(1 - distance, stroke.Falloff);
                result = Mathf.Clamp01(result + stroke.Amount * weight);
            }
            Vector3 world = _surface.transform.TransformPoint(localPosition);
            foreach (var exclusion in _exclusions)
            {
                if (exclusion)
                {
                    result *= exclusion.Sample(world);
                }
            }
            return result;
        }
    }
}
